### ISSUE TITLE
Twilio credentials open to the world

### ISSUE THREAD

**Issue by simpss** [mcwebb/angular-twilio#1]
Hey, just a small thing i noticed while checking this. 
If you deploy this to a public server, the twilio credentials are viewable to the world.

**Comment by mcwebb** [comment]
Hey @simpss, that's very true, thanks!
I use the module as part of a Cordova app, so it isn't so much of an issue, but I'll add a warning to the readme about this.
As far as I know this is always an issue with consuming APIs from client side JavaScript, or is there a work around?

**Comment by mcwebb** [comment]
warning added in 399db99
